language: node_js
node_js:
  - "10"
  - "11"
  - "12"
install:
  - npm i
  - npm install -g codecov
cache:
  directories:
    - node_modules
script:
  - jsipfs init
  - npm test
  - codecov
services: mongodb
