version: "3"

services:
  mongo:
    image: mongo
    hostname: mongo
    restart: unless-stopped
    volumes:
      - dbdata:/data/db
    expose:
      - "27017"
    ports:
      - "27017:27017"

  quasar:
    build:
      context: .
      dockerfile: Dockerfile
    image: quasar
    container_name: quasar
    restart: unless-stopped
    links:
      - mongo
    ports:
      - "3001:3001"
    volumes:
      - .:/home/node/quasar
      - node_modules:/home/node/quasar/node_modules
    env_file: .env
    environment:
      WAIT_HOSTS: mongo:27017
      DB_URL: mongodb://mongo:27017/quasar

volumes:
  dbdata:
  node_modules:
